### ISSUE TITLE
run FWI_main.py

### ISSUE THREAD

**Issue by Brown2Wang** [YangFangShu/FWIGAN#3]
maximum value of true model:  tensor(5772.3960, device='cuda:0')
Initial model exists, downloading...
Initial source amplitude exists, downloading...
Start to generate the clean receiver amplitudes......
Traceback (most recent call last):
  File "FWI_main.py", line 132, in <module>
    receiver_amplitudes = createdata(model_true,dx,source,x_s,x_r,dt,pml_width,order,survey_pad,device).to(device)
  File "/content/drive/MyDrive/GPU/FWIGAN/FWIGAN/utils/utils.py", line 153, in createdata
    receiver_amplitudes = prop(source_amplitudes.to(device),x_s.to(device),x_r.to(device),dt).to(device)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepwave-0.0.8-py3.7-linux-x86_64.egg/deepwave/base/propagator.py", line 138, in forward
    model = self.extract(self.model, source_locations, receiver_locations)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepwave-0.0.8-py3.7-linux-x86_64.egg/deepwave/base/extract.py", line 32, in forward
    survey_pad = _set_survey_pad(self.survey_pad, model.ndim)
  File "/usr/local/lib/python3.7/dist-packages/deepwave-0.0.8-py3.7-linux-x86_64.egg/deepwave/base/extract.py", line 50, in _set_survey_pad
    if not all((pad is None) or (pad >= 0) for pad in survey_pad):
TypeError: 'int' object is not iterable

**Comment by HuokyGit** [comment]
I also encountered the same problem. How did you solve it.
