### ISSUE TITLE
运行fwi文件一直出现这个问题，难以解决，删掉有关内容后反演模型无法出现，这个问题难以解决哭了，下边是报的错

### ISSUE THREAD

**Issue by quanzhunideyang** [YangFangShu/FWIGAN#6]
maximum value of true model:  tensor(4700., device='cuda:0')
Start to generate the initial model
model size: torch.Size([117, 567])
Start to generate the source amplitude
Start to generate the clean receiver amplitudes......
Traceback (most recent call last):
  File "FWI_main.py", line 132, in <module>
    receiver_amplitudes = createdata(model_true,dx,source, \
  File "/root/FWIGAN/FWIGAN/FWIGAN/utils/utils.py", line 153, in createdata
    receiver_amplitudes = prop(source_amplitudes.to(device), \
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/deepwave/base/propagator.py", line 138, in forward
    model = self.extract(self.model, source_locations, receiver_locations)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/deepwave/base/extract.py", line 32, in forward
    survey_pad = _set_survey_pad(self.survey_pad, model.ndim)
  File "/root/miniconda3/lib/python3.8/site-packages/deepwave/base/extract.py", line 50, in _set_survey_pad
    if not all((pad is None) or (pad >= 0) for pad in survey_pad):
TypeError: 'int' object is not iterable

**Comment by YangFangShu** [comment]
this problem is may cased by the wrong installation of deepwave. please redo it follwing our guide.

**Comment by quanzhunideyang** [comment]
> this problem is may cased by the wrong installation of deepwave. please redo it follwing our guide.
非常谢谢，果然是这个包有问题，改动一点都不行
